services:
  stagebot-discord-app:
    build:
      context: .
    environment:
      NODE_ENV: production
    image: node:22.10.0-alpine3.20 
  stagebot-db:
    image: mysql:8.0.37
    environment:
      MYSQL_DATABASE: smashultimatesingles
      MYSQL_USER: stagebot
      MYSQL_PASSWORD: IPlayF0x
      MYSQL_ROOT_PASSWORD: IMainmar10
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3307:3306"
volumes:
  db_data:
